TASK 1

In [31]:
import cv2
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Load the image
image = cv2.imread('sample.jpg', cv2.IMREAD_GRAYSCALE)

# Perform FFT on the image
f_transform = np.fft.fft2(image)
fshift = np.fft.fftshift(f_transform)

# Display the FFT image
cv2.imshow('Filtered Image', np.abs(fshift.astype(np.uint8)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
# Create a horizontal line filter
rows, cols = image.shape
filter = np.zeros_like(image)

filter[rows // 2 - 2:rows // 2 + 2, :] = 1

# Apply the filter in the frequency domain
filtered_image = fshift * filter
filtered_image = np.fft.ifftshift(filtered_image)
filtered_image = np.fft.ifft2(filtered_image)
filtered_image = np.abs(filtered_image)

# Display the filtered image
cv2.imshow('Horizontal Line Filtered Image', filtered_image.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()


In [33]:
# Create a vertical line filter
filter = np.zeros_like(image)
filter[:, cols // 2 - 2:cols // 2 + 2] = 1

# Apply the filter in the frequency domain
filtered_image = fshift * filter
filtered_image = np.fft.ifftshift(filtered_image)
filtered_image = np.fft.ifft2(filtered_image)
filtered_image = np.abs(filtered_image)

# Display the filtered image
cv2.imshow('Vertical Line Filtered Image', filtered_image.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()


In [34]:
# Create a diagonal line filter
filter = np.zeros_like(image)
np.fill_diagonal(filter, 1)

# Apply the filter in the frequency domain
filtered_image = fshift * filter
filtered_image = np.fft.ifftshift(filtered_image)
filtered_image = np.fft.ifft2(filtered_image)
filtered_image = np.abs(filtered_image)

# Display the filtered image
cv2.imshow('Diagonal Line Filtered Image', filtered_image.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()


TASK 2

In [22]:
# Define the filters
laplacian_kernel = np.array([[0, -1, 0],
                             [-1, 4, -1],
                             [0, -1, 0]])

prewitt_horizontal_kernel = np.array([[-1, -1, -1],
                                      [0, 0, 0],
                                      [1, 1, 1]])

prewitt_vertical_kernel = np.array([[-1, 0, 1],
                                    [-1, 0, 1],
                                    [-1, 0, 1]])

sobel_horizontal_kernel = np.array([[-1, -2, -1],
                                    [0, 0, 0],
                                    [1, 2, 1]])

sobel_vertical_kernel = np.array([[-1, 0, 1],
                                  [-2, 0, 2],
                                  [-1, 0, 1]])

average_kernel = np.ones((3, 3), np.float32) / 9  # 3x3 average filter

In [27]:
filters = [laplacian_kernel,prewitt_horizontal_kernel,prewitt_vertical_kernel,sobel_horizontal_kernel,sobel_vertical_kernel,average_kernel]
names = ["laplacian_kernel","prewitt_horizontal_kernel","prewitt_vertical_kernel","sobel_horizontal_kernel","sobel_vertical_kernel","average_kernel"]

In [30]:
# Perform FFT on the filter
for name,filter in zip(names,filters):
        f_transform = np.fft.fft2(filter)
        fshift = np.fft.fftshift(f_transform)
        print(name,'\n',np.abs(fshift),'\n')

laplacian_kernel 
 [[6. 3. 6.]
 [3. 0. 3.]
 [6. 3. 6.]] 

prewitt_horizontal_kernel 
 [[0.         5.19615242 0.        ]
 [0.         0.         0.        ]
 [0.         5.19615242 0.        ]] 

prewitt_vertical_kernel 
 [[0.         0.         0.        ]
 [5.19615242 0.         5.19615242]
 [0.         0.         0.        ]] 

sobel_horizontal_kernel 
 [[1.73205081 6.92820323 1.73205081]
 [0.         0.         0.        ]
 [1.73205081 6.92820323 1.73205081]] 

sobel_vertical_kernel 
 [[1.73205081 0.         1.73205081]
 [6.92820323 0.         6.92820323]
 [1.73205081 0.         1.73205081]] 

average_kernel 
 [[0.         0.         0.        ]
 [0.         1.00000001 0.        ]
 [0.         0.         0.        ]] 



TASK 3


In [19]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('Stacked_img.jpeg', cv2.IMREAD_GRAYSCALE)

# Perform FFT on the image
f_transform = np.fft.fft2(image)
fshift = np.fft.fftshift(f_transform)

# Create a Gaussian blur filter in the frequency domain
rows, cols = image.shape
crow, ccol = rows // 2, cols // 2
D = 50  # Blur radius
H = np.zeros_like(image, dtype=complex)
for i in range(rows):
    for j in range(cols):
        dist = np.sqrt((i - crow) ** 2 + (j - ccol) ** 2)
        H[i, j] = np.exp(-dist**2 / (2 * D**2))

# Apply the filter in the frequency domain
filtered_image = fshift * H
filtered_image = np.fft.ifftshift(filtered_image)
filtered_image = np.fft.ifft2(filtered_image)
filtered_image = np.abs(filtered_image)

# Display the filtered image
cv2.imshow('Filtered Image', filtered_image.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()


TASK 4

In [21]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image
image = cv2.imread('Stacked_img.jpeg', cv2.IMREAD_GRAYSCALE)

# Perform FFT on the image
f_transform = np.fft.fft2(image)
fshift = np.fft.fftshift(f_transform)

# Create a filter to enhance edges (e.g., high-pass filter)
rows, cols = image.shape
crow, ccol = rows // 2, cols // 2

# Define the size of the high-pass filter
D = 10

# Create a high-pass filter in the frequency domain
H = np.zeros_like(image, dtype=complex)
for i in range(rows):
    for j in range(cols):
        dist = np.sqrt((i - crow) ** 2 + (j - ccol) ** 2)
        if dist > D:
            H[i, j] = 1

# Apply the filter in the frequency domain
filtered_image = fshift * H
filtered_image = np.fft.ifftshift(filtered_image)
filtered_image = np.fft.ifft2(filtered_image)
filtered_image = np.abs(filtered_image)

# Display the filtered image
cv2.imshow('Filtered Image', filtered_image.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()